### ISSUE TITLE
Kuma DP image pull secret is missing

### ISSUE THREAD

**Issue by brunda-bs** [kumahq/kuma#10944]
### What happened?

Hi,

We are using a private registry to pull the Kuma DP image using an image pull secret. The global image pull secret configuration works fine for Kuma CP, ingress, and egress. However, for Kuma DP,  The global image pull secret specified in the Kuma Helm chart is not present in the application pod configuration being generated. 

Some app pods come up because the image is present on the node, as the image pull policy is "IfNotPresent." Even though "Always" has been set in the Helm chart, it's not being overridden.

We encounter image pull back off errors for delegated gateway pods as well as it uses kuma-dp.

**Comment by lahabana** [comment]
This makes sense.

One way to work around this is to use `ContainerPatches`: https://kuma.io/docs/dev/production/dp-config/dpp-on-kubernetes/#custom-container-configuration

**Comment by brunda-bs** [comment]
Hi @lahabana,

The container patch is not helping to update the image pull secret. As imapge pull secret is pod level configuration not sidecar level. 
Can you please help here?

**Comment by bartsmykla** [comment]
> triage: how are you solving this issue for regular applications? If it's a pod level configuration why it cannot be applied on a workload definition (deployment, daemonset etc.)?

**Comment by jijiechen** [comment]
@bartsmykla This is a valid case as the application workload can be created by different teams and they can not easily be standarlized with the pull secret attached on each of them. However this is only an issue when `kuma-sidecar` images are limited to certain users with permissions within your privite registry rather than open to all users. 

Given that said, @brunda-bs can you consider opening the permission to pull of `kuma-*` images to your internal users? Pull secrets are grouped by hostnames on Kubernetes, if we provide the capability of injecting a pre-set image pull secret to the pod level the secret may be conflicting to your application containers if they specify other pull secrets to pull their own images from the same hostname.

**Comment by brunda-bs** [comment]
Hi @jijiechen ,

we will check if we can add permission to pull Kuma images. Until we have a process around it, is it possible to use a different registry for kuma dp and kuma cp in the zone tenant cluster?

I see we can only specify one global registry in the helm chart.

**Comment by jakubdyszkiewicz** [comment]
> is it possible to use a different registry for kuma dp and kuma cp in the zone tenant cluster?

Hey, yes. Take a look at
https://github.com/kumahq/kuma/blob/master/pkg/config/app/kuma-cp/kuma-cp.defaults.yaml#L260
https://github.com/kumahq/kuma/blob/master/pkg/config/app/kuma-cp/kuma-cp.defaults.yaml#L327
https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/values.yaml#L4

The last one should not affect injected kuma-dp registry. You should also be able to specify it just for control plane with `controlPlane.image.registry`

**Comment by brunda-bs** [comment]
Hi @jakubdyszkiewicz ,

I notice that the Helm chart for Kuma only allows the registry to be specified globally. There's no option for controlPlane.image.registry in the chart.
- https://artifacthub.io/packages/helm/kuma/kuma

For both kuma dp and init container registry option is not there either. Only image name is present.

https://github.com/kumahq/kuma/blob/master/pkg/config/app/kuma-cp/kuma-cp.defaults.yaml#L260
https://github.com/kumahq/kuma/blob/master/pkg/config/app/kuma-cp/kuma-cp.defaults.yaml#L327

**Comment by michaelbeaumont** [comment]
Hi @brunda-bs , it's not documented in `values.yaml` but in fact you can set `controlPlane.image.registry` and [it's taken into account in the templates](https://github.com/kumahq/kuma/blob/0a366462a9988831e4d179f2a29ea6a5be0540e5/deployments/charts/kuma/templates/_helpers.tpl#L160).

**Comment by brunda-bs** [comment]
Hi @michaelbeaumont ,

Thanks for your response.

I tried adding the `controlPlane.image.registry`, although cp pods are able to point the private registry, Image pull secret is not being picked up by `controlPlane.image.imagePullSecrets`

**Comment by michaelbeaumont** [comment]
Right, there is no control plane specific `imagePullSecrets`.

**Comment by slonka** [comment]
@michaelbeaumont - are we planning on adding them then?

**Comment by slonka** [comment]
> Triage: @brunda-bs - does it work for you or do you still need help? If yes, can you summarise what you've tried and what you wanted to achieve? Also can you sum up why none of the suggested options worked for you?

**Comment by brunda-bs** [comment]
Hi @slonka ,

Once I changed the repository to a private one, I tried to add an image pull secret through Helm using the imagepullsecret key. However, since it is a deployment level configuration(instead container level) it didn't work.

If the application deployment has the image pull secret(non-harming change), the Kuma dp image is getting pulled successfully.

**Comment by jakubdyszkiewicz** [comment]
> Triage: at this point, we are not sure what's the solution here. Could you open a PR with a suggested change?

**Comment by lukidzi** [comment]
I’m closing the issue for now. If it still seems relevant, feel free to reopen it.

**Comment by Frederickl78** [comment]
Since [docker.io](http://docker.io/) is now throttled (Unauthenticated users: 100 per IPv4 address per 6 hours), I'm trying to use a private registry for kuma images: kuma-cp, kuma-dp, kuma-init, kumactl and bitnami/kubectl.

No problem for control plane and ingress controller; I have a secret named "registry-secret" to pull docker images.
I've synced that secret in all namespaces that contains resources that must have a sidecar (each pods adding kuma-sidecar must pull kuma-init and kuma-dp).

Here's my helm upgrade --install command for the zones:
helm upgrade --install kuma --create-namespace --namespace kuma-system \
   --set controlPlane.mode=zone \
   --set controlPlane.zone=$ZONE_NAME \
   --set ingress.enabled=true \
   --set "controlPlane.kdsGlobalAddress=grpcs://$GLOBAL_CP_IP:5685" \
   --set "controlPlane.tls.kdsZoneClient.skipVerify=true" \
   --version=$KUMA_VERSION \
   --set "global.imagePullSecrets[0]=registry-secret" \
   --set "global.image.tag=$KUMA_VERSION" \
   --set "global.image.registry=[my.pr](http://my.pr/)ivate.registry" \
   --set "controlPlane.image.repository=$DOCKER_REPO/kumahq/kuma-cp" \
   --set "dataPlane.image.repository=$DOCKER_REPO/kumahq/kuma-dp" \
   --set "dataPlane.initImage.repository=$DOCKER_REPO/kumahq/kuma-init" \
   --set "kumactl.image.repository=$DOCKER_REPO/kumahq/kumactl" \
   --set "kubectl.image.registry=my.private.registry" \
   --set "kubectl.image.repository=$DOCKER_REPO/bitnami/kubectl" \
   --set "kubectl.image.tag=1.27.5" \
   --set controlPlane.replicas=2 \
   kuma/kuma

With this config, I assume (maybe Im wrong) that pods sidecar will be able to pull kuma-init and kuma-dp from private repository if secret "registry-secret" is in the namespace?
Until now, sometimes I have ImagePullBackoff , sometimes it works and my only guess is that image is be present on node in thoses cases.

I can see the pod trying to pull "$DOCKER_REPO/kumahq/kuma-init" but fails with a 403 - unauthorized.

**Comment by lukidzi** [comment]
> Triage: let's verify how we are doing it and provide example how to use private registry
