### ISSUE TITLE
Scaling prometheus as data planes scales

### ISSUE THREAD

**Issue by sudeeptoroy** [kumahq/kuma#1146]
For universal mode, prometheus-sd does end point discovery with control plane and prometheus scrape the data plane. 
As more data planes continue to join the mesh prometheus might need to scale. Additionally it would be a good idea to shard the prometheus instance to take care of scaling data planes. 
Do you have any recommendations for such scenario?

**Comment by lahabana** [comment]
The now recomended way is to use the builtin [kuma-sd](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kuma_sd_config).
I don't think Kuma should take care of auto-scaling prometheus, optionally using a scaling prometheus like [Cortex](https://cortexmetrics.io/) would be an alternative.
This is why this issue is getting closed.
