### ISSUE TITLE
Service identity injection to request payload

### ISSUE THREAD

**Issue by rucciva** [kumahq/kuma#1256]
### Summary

A service might implement a custom Accounting logic. Meanwhile in service mesh scenario, it is preferred to delegate Authentication and Authorization to the data plane, making the receiving service unaware of the caller identity. Thus it would be preferable if the caller identity can be made available to the receiving service, .e.g through HTTP header injection.

### Additional Details & Logs

- Version: 1.0.1
- Error logs: -
- Configuration: -
- Platform and Operating System: -

**Comment by subnetmarco** [comment]
This would be quite simple to implement, I would assume (at least for HTTP requests). We could be returning two headers:

* `X-Forwarded-Client-Cert`, with the full Spiffe entry.
* `X-Forwarded-Client-Service`, with the service name only.

And perhaps:

* `X-Forwarded-Client-Zone`, with the service zone name only.

**Comment by slonka** [comment]
Just a couple of things to keep in mind when implementing this:

If you want the full spiffie entry you can use https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-setcurrentclientcertdetails and set the type to URI (side note: from my experience developers do not want the full spiffie entry, and making everyone parse that themselves is pointless).

For the service name you have to manually extract it. The SAN URI part is available via Lua scripts, an example usage is here: https://github.com/allegro/envoy-control/blob/master/envoy-control-core/src/main/resources/lua/ingress_client_name_header.lua#L12 , but make sure you use Envoy version higher than 59e29685d33bd730c76ccb3b8383b666c0942523 (a couple of commits after 1.16.0) otherwise you’ll encounter Envoy SEGFAULT after a couple of requests pass through that script (details here: https://github.com/envoyproxy/envoy/pull/14092).

Kuma identifies services by SAN URI: spiffe://{mesh}/{service} so additional question to @subnetmarco - by “service zone” name only you mean the first part of the URI “{mesh}“ right?

**Comment by nickolaev** [comment]
Thanks for the pointers @slonka. We have already adopted envoy 1.16.1, so that should not be a problem.
About your last question, I guess @subnetmarco referees to the kuma `multi-zone` deployments, where we have distributed/hybrid deployments. So a zone would be something like `dc-us-east` or `dc-eu-north`.

**Comment by slonka** [comment]
@nickolaev I'm sorry I was mistaken v1.16.1 was released `2020-11-20 18:43:35 -0800` and that fix was merged `2020-11-23 09:54:37 +0100` so you still need to upgrade if you want to use that feature.

**Comment by jewertow** [comment]
I will work on this issue.

**Comment by jewertow** [comment]
@rucciva you can get service identity from the header `x-forwarded-client-cert`. This header has the following content:
```
X-Forwarded-Client-Cert By=spiffe://default/backend;Hash=232f6d6d848c69b2877b7cc643b8cbd5f843c4a9d51daf9ba7160d7342cf0b3e;URI=spiffe://default/frontend
```
So you can parse this header, get `URI` and retrieve name of the service.

I will come back to this feature the next week and I will implement headers proposed by @subnetmarco.

@slonka thank you very much for your hints. They were very helpful.

**Comment by rohank2002** [comment]
I see that that the pull request was [merged](https://github.com/kumahq/kuma/pull/1941), is this issue resolved? I was testing internal mtls using Kuma. I used a [podinfo](https://github.com/stefanprodan/podinfo) deployment for getting the headers from the request. I couldn't see the XFCC header.

**Comment by lahabana** [comment]
I think the issue is still open because the implementation was never completed. @jakubdyszkiewicz do you have more ctx?

**Comment by slonka** [comment]
The issue is still open because this was not merged: https://github.com/kumahq/kuma/pull/2158#issuecomment-990058670 right?

Side note: I'm really surprised this feature is not requested more often. `Envoy-control` shipped with mTLS on `4 Jun 2020` and the equivalent feature was implemented right after that (on `27 Nov 2020`).

**Comment by scottslowe** [comment]
+1 for finishing up the implementation of this functionality

**Comment by slonka** [comment]
For these headers to be injected `appProtocol` needs to be set to `http` https://kuma.io/docs/1.7.x/policies/protocol-support-in-kuma/#protocol-support-in-kuma

**Comment by whiskeysierra** [comment]
> For these headers to be injected `appProtocol` needs to be set to `http` https://kuma.io/docs/1.7.x/policies/protocol-support-in-kuma/#protocol-support-in-kuma

Shouldn't `grpc` work as well?

**Comment by slonka** [comment]
> Shouldn't grpc work as well?

you're right, it just needs to be different than `tcp`

**Comment by slonka** [comment]
AFAIK this is solved (with the full entry, clients have to extract name manually), you just need to make sure you mark the app with protocol http/grpc. Closing, if something does not work please reopen.
