### ISSUE TITLE
Can we have kuma CRDs as namespace scoped?

### ISSUE THREAD

**Issue by nikita15p** [kumahq/kuma#1366]
### Summary

Currently kuma has CRDs cluster scoped, can we have it namespace scoped as defined in https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/ .

### Steps To Reproduce
Browse to https://github.com/kumahq/kuma/tree/master/deployments/charts/kuma/crds to check scope.
eg In https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/circuit-breaker.yaml
![image](https://user-images.githubusercontent.com/37657012/103069392-4d33cd80-45e5-11eb-8d19-efb362adfbde.png)

And https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/data-planes.yaml, https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/crds/data-planes.yaml have `scope: ""`
### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by austince** [comment]
Hey @nikita15p, can you describe a bit of your use case for needing Namespaced-scoped CRDs and why the current scope doesn't work for you?

**Comment by nikita15p** [comment]
Hi @austince . I am looking for CRDs at namespace scope, because same cluster is being used by multiple tenants and applications being namespaced. So CRDs at namespaced scope is more apt and can be created by users without cluster-level authorizations.

**Comment by austince** [comment]
Got it, thanks! Are you thinking of having multiple Kuma control-planes running in the same cluster? Can you describe a bit more about how different users deploy apps and Kuma resources?

**Comment by nikita15p** [comment]
So basically few of the users may need kuma service mesh while others may not use service mesh or will opt for other service mesh. So having namespace scoped CRDs will be simpler to use and reduce overhead of cluster-level auth. And yes, if it's available at namespace scope, we can have multiple control planes in same cluster (for eg maintaining standalone mode in one namespace and multizone mode in another namespace of same cluster, one control plane in k8s mode while other in universal mode, etc)

**Comment by austince** [comment]
That makes sense to me, thanks for the extra info! I'm not entirely sure what the current constraints are -- @jakubdyszkiewicz / @nickolaev will be swamped with notifications over the next few days (weeks? :sweat_smile:) but could hopefully shed more light on why the resources are cluster-scoped.

My initial guess, which could be way off, is that the Kuma control-plane currently watches resources in the entire cluster, not per-namespace, and then filters namespaces on if the `kuma.io/sidecar-injection: true` annotation exists, so a decent amount of work would be needed to refactor the control-plane to watch a single namespace.

**Comment by jakubdyszkiewicz** [comment]
Hey @nikita15p 

our motivation to get change namespace scoped resources to cluster scoped was that it was confusing for users to understand in which namespace they should put policies and how does it affect the traffic. Internally we were omitting this information altogether (because you can have one mesh on many namespaces) so we decided that it makes the most sense to change the scope to Cluster.

Supporting multiple control planes in one cluster will be difficult but not impossible to achieve. You would need to have some extra annotations aside of `kuma.io/sidecar-injection: true` to indicate to which control plane the data plane should connect to. On top of that, we need to know which control plane should manage resources from which namespace (validation, events, etc.). Our experience so far is that one team (infrastructure) in the organization is responsible for a service mesh. Developer teams seem to be fine "sharing" Kuma in one cluster and you still can control injection with the `kuma.io/sidecar-injection`. Because of Mesh separation, you can always create a completely separate Mesh to not interfere with other deployments.

Having remote in one namespace and global in another is a real use case, but we have plans to introduce a mode that can be global and remote at the same time, so it's easier for users to convert standalone deployment into multizone.

I'd like to learn more about `cluster-level auth` and how cluster-scoped resources are inconvenient here. Wouldn't access to the resources be as simple as defining `ClusterRoleBinding` that will allow CRUD resources for a given user?

Thanks!

**Comment by nikita15p** [comment]
Thanks for the detailed explanation. Getting cluster-level auth for a user in the shared cluster needs admin privilege and has to go through process of org.

**Comment by thirdeyenick** [comment]
We would also like to have the kuma CRDs being namespaced. One idea we had was a global control plane per team (all of them deployed in one k8s cluster). That way we could actually update control planes per team and not all of them at once.

We also noticed that every remote control plane gathers all available mesh CA certificates and keys from the global control plane and stores them locally in the cluster. If a cluster isn't using a certain mesh at all, it might be a security risk to have the secrets in that cluster. RBAC might be used to secure the namespace and those secrets, but it would still be better to not have secrets for "foreign" meshes in the cluster at all. By running multiple global control planes and also multiple remote control planes (if one cluster wants to take part in multiple meshes), we could separate everything between teams.

**Comment by jakubdyszkiewicz** [comment]
Right now we are rethinking some design choices of Multizone. We definitely will take this into consideration

**Comment by lahabana** [comment]
This is fully covered in #2921 so closing as dupe
