### ISSUE TITLE
Support running multizone global and zone CPs in the same k8s cluster

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#1496]
### Summary

Id like to be able to deploy multizone global CP and remote CP to the same k8s cluster

### Steps To Reproduce

1. Deploy global multizone CP to a k8s cluster
2. Deploy remote multizone CP to the same k8s cluster. This is not possible as of 1.0.6
3.
4.

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by coreywagehoft** [comment]
I would like to see Kuma support this so that we don't have to operate a completely separate Kubernetes cluster for the global control plane.

**Comment by lahabana** [comment]
xrefs:
- #3247 
- #2921
- #2780
- #738

**Comment by lahabana** [comment]
This is planned but we first need to move all the policies to be namespace scoped.

**Comment by lahabana** [comment]
Policies still needing to be migrated:

deployments/charts/kuma/crds/kuma.io_externalservices.yaml:
deployments/charts/kuma/crds/kuma.io_meshes.yaml:
deployments/charts/kuma/crds/kuma.io_meshgatewayconfigs.yaml:
deployments/charts/kuma/crds/kuma.io_meshgateways.yaml:
deployments/charts/kuma/crds/kuma.io_serviceinsights.yaml:
deployments/charts/kuma/crds/kuma.io_virtualoutbounds.yaml:
deployments/charts/kuma/crds/kuma.io_zoneinsights.yaml:
deployments/charts/kuma/crds/kuma.io_zones.yaml:


- All our configMaps/Secrets are namespace scoped already.
- Need to figure out a way to deal with webhooks. (Does a namespace have a zone reference?) -- Only needed to run multiple zones in the same cluster.
- Tests

**Comment by lahabana** [comment]
Random thoughts we had with @jakubdyszkiewicz : 

- We can do so that KDS figures that the synced cluster scope resources are already in the cluster (using uid for example, or just not fetching them with an explicit flag)
- We can skip reconciling policies in other namespaces annotated with `kuma.io/system-namespace: true`
- Webhooks remains a question or maybe it just relies on system-namespace too or global has a webhook only for its system namespace.

The only reason for not having mesh cluster scope seems to be able to do this, which in the end might possible even with cluster scoped policies.

**Comment by slonka** [comment]
Isn't this partly solved by https://github.com/kumahq/kuma/issues/5907 ? The original issue did not say that both of them have to be backed by k8s storage.

**Comment by jakubdyszkiewicz** [comment]
> Triage: it's about deploying global and zone cp with k8s storage

**Comment by lahabana** [comment]
Is this something people still ask for?

**Comment by slonka** [comment]
> Triage: closed, let's reopen if needed
