### ISSUE TITLE
Add ability to pass --concurrency to envoy

### ISSUE THREAD

**Issue by jgrund** [kumahq/kuma#1721]
It would be useful to be able to set the `--concurrency` flag via `kuma-dp` when it invokes `envoy`. It does not appear possible to customize this value otherwise.

**Comment by jgrund** [comment]
For some more background, I have some low-traffic services that I am deploying on a node with 255 hardware threads.

Envoy allocates a worker thread for every hardware thread in the system by default. 
Each hardware thread will have around 4 file-descriptors open. Overall, each envoy instance ends up taking 1050 file descriptors on this system (1,020 for the threaded workers + some overhead).

I don't need this many workers idling. perhaps we could have an environment variable / cli arg passed to `kuma-dp` that will set the `--concurrency` flag?

**Comment by jakubdyszkiewicz** [comment]
This can be more generally solved with this https://github.com/kumahq/kuma/issues/1920

**Comment by jpeach** [comment]
Re-opening.

In light of the discussion in #1920, I think that it's worth implementing this as a standalone improvement. Here's my proposal:

1. Add a `--concurrency` flag to `kuma-cp` that accepts either a numeric argument, or the strings "default" or "auto". "default" is the default :)
2. The "default" concurrency means to omit the Envoy flag, though in this case we will always pass `--cpuset-threads`, since that just makes sense IMHO.
3. The "auto" concurrency means to probe for cgroup resources and automatically scale concurrency. I don't propose to implement that yet, just reserving the argument value.
4. In the Kubernetes sidecar injector, automatically set the concurrency based on the [configured resources](https://github.com/kumahq/kuma/blob/master/pkg/plugins/runtime/k8s/webhooks/injector/injector.go#L253), with a floor of 2.
5. Add Kubernetes support for a `kuma.io/sidecar-proxy-concurrency` to allow users to override the automatic concurrency setting.

So with this machinery, Universal deployments have a manual tunable, or can mitigate the default using cpusets. Kubernetes defaults will auto configure by default, and can manually tune with annotations or control plane config

We can still add a `concurrency` field to the Dataplane resource later, if there's a use case for that.
