### ISSUE TITLE
Support configuration of prometheus fields 

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#1942]
### Summary

I'd like to be able to configure/limit the fields created for prometheus queries. For example, kuma-prometheus-sd creates the following which has several duplicate singular and plural fields (e.g. kuma_io_zone, kuma_io_zones)

```
    {
        "targets": [
            "ip-172-31-29-90.us-east-2.compute.internal:5670"
        ],
        "labels": {
            "__metrics_path__": "/metrics",
            "__scheme__": "http",
            "dataplane": "internalhttpbin-52i8jq",
            "instance": "internalhttpbin-52i8jq",
            "job": "echo-service_default_svc_8080",
            "kuma_io_protocol": "http",
            "kuma_io_protocols": ",http,",
            "kuma_io_service": "echo-service_default_svc_8080",
            "kuma_io_services": ",echo-service_default_svc_8080,",
            "kuma_io_zone": "universal-1",
            "kuma_io_zones": ",universal-1,",
            "mesh": "default"
        }
    }
```

**Comment by subnetmarco** [comment]
@kumahq/kuma-maintainers any thoughts on this issue?

**Comment by jpeach** [comment]
Looks a bit like `kuma_io_zone` and `kuma_io_zones` are different metrics, but appear similar because there's only one zone?

**Comment by austince** [comment]
They are actually the same metric – the names are automatically "plural-ized" here: https://github.com/kumahq/kuma/blob/19d3b806b63edf388d9a690be3282555cf1d8f5c/pkg/mads/util.go#L29-L59

This was done by @ yskopets I believe, and am not sure if it is totally necessary. Whether we remove that feature is independent of this ask though, I think, which I would recommend as a "wont-fix" since it should be done on the Prometheus side.
