### ISSUE TITLE
Is it possible to add basic authentication for microservices?

### ISSUE THREAD

**Issue by debu99** [kumahq/kuma#1986]
Does Kuma support adding basic authentication for microservices?

**Comment by codyde** [comment]
Hi debu99! Kuma itself doesn't support basic auth between services in the OSS product. I don't mean to plug the enterprise product on here at all - but we do have OPA integration in Kong Mesh which allows you to leverage JWT tokens in the service communication path, but I wouldn't call that basic authentication either. Kong Gateway has some authentication capabilities - so that might be an answer as well. 

Can you talk a little bit more about what you're looking for so we can get a better picture?

**Comment by debu99** [comment]
Thanks codyde, we already use Kong with basic auth for north & south traffic, since we would like to use kuma for east/west traffic, so we need to explorer is this possible, but anyway, thanks for the info, I will check the OPA
