### ISSUE TITLE
Align issue templates and labels across the Kuma org.

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2429]
### Summary

There's a bit of management overhead foe every repository in the organization around managing issue templates, labels and other metadata. We can amortize this in a few ways

1. A `.github` repository can share common [community health files](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file) and templates ([example here](https://github.com/github/.github))
2. The Prow [label sync](https://github.com/kubernetes/test-infra/tree/master/label_sync) tool can migrate labels to a common set across all the repositories

What we would need for this is a new `.github` and copy the standard files from the kuma org to there. Adding the [templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests) in the `.github/.github` directory will let other repositories automatically pick them up.

The label sync work is similar. We need to run a cron action on the `.github` repository that would sync the labels across the org. The job should run as a group that has write access to all the repositories. I'd suggest that we also align the labels into a Kubernetes-style vocabulary at that time (the tooling will take care of migrating existing labels).

**Comment by jpeach** [comment]
cc @tomaszwylezek @Bradamant3 @subnetmarco @lobkovilya @jakubdyszkiewicz @bartsmykla for discussion :)

**Comment by jpeach** [comment]
xref #2494

**Comment by Bradamant3** [comment]
Can we add the actual DCO text file as part of this effort? (again across repos in the org -- DCO requirement is completely missing from kuma-website, but it's not exactly clear or complete for kuma, either)

**Comment by jpeach** [comment]
@lahabana Please update this to summarize the recent org changes you made to the kuma respositories.

**Comment by lahabana** [comment]
A lot of this has indeed been done in: https://github.com/kumahq/.github


1. The community files are added and a [job syncs the files](https://github.com/kumahq/.github/blob/main/.github/workflows/wfc_lifecycle.yml#L133-L159)  (the github community files doesn't add the file in the repo and doesn't sync LICENSE which is requirement from CNCF which is why there's a workflow).
2. There's a label [sync job](https://github.com/kumahq/.github/blob/main/.github/workflows/wfc_lifecycle.yml#L108-L132) which is inspired but not copied from the k8s tool because the k8s tool is not really meant to be used outside of k8s.

Each repo now has 2 files to define labels:

- [`org_labels.yml`](https://github.com/kumahq/.github/blob/main/org_labels.yml) synced from .github and is a list of common labels shared everywhere!
- [`labels.yml`](https://github.com/kumahq/.github/blob/main/labels.yml) labels used inside in the specific repo.

More information on this in [PROJECT_MANAGEMENT.md](https://github.com/kumahq/.github/blob/main/PROJECT_MANAGEMENT.md).

I believe this covers what's mention in this so closing it. If not please open another issue in kumahq/.github :)
