### ISSUE TITLE
Multi region kds sync stops with a lot of dataplanes

### ISSUE THREAD

**Issue by bchatelard** [kumahq/kuma#2492]
### Summary

The kds stream seams to stop sending/receiving updates to some clients when there is a lot of dataplanes (> 200).

### Steps To Reproduce

I have only been able to reproduce using real sidecars in staging environment (I think it might be related to the frequency of the dataplane insight update).

1. Create 2 dps, 1 global, 1 zone.
2. Create 200 meshes.
3. Create 200 dataplanes and launch the sidecars / kuma-dp process.
4. Create a new mesh, the mesh is not propagated to the zone.

### Additional Details & Logs

There is no error logs, the global seems to try to send the update to the zone, but the zone never receive the updates.
The counters of the zone insight stays to 1 sent, and is never acknowledged.

- Version 1.2.3
- No errors in the log, just hanging
- Linux
- Manual install
- I tried to bump the max grpc payload, but it was not working. (I dont have the error).

**Comment by lahabana** [comment]
I'll come back and add more info.
But from looking a bit it seems that there are multiple writes coming from different goroutines.
This is not tolerated by go-grpc ([docs](https://github.com/grpc/grpc-go/blob/master/Documentation/concurrency.md#streams)).

The problem seems to be reusing the same grpc stream for go-control-plane and the discovery request/response.

**Comment by lahabana** [comment]
I believe I have managed to reproduce this issue in a test.
The multiplex client ensures that recv is done in a single goroutine but that's not the case for send calls.

I have an idea on how to fix this I hope to get a PR out soon.

**Comment by bchatelard** [comment]
I just tested the linked PR (cherry-pick in 1.2.3) and it looks like it is solving this issue.
