### ISSUE TITLE
Converge `get` and `inspect` in the CLI

### ISSUE THREAD

**Issue by subnetmarco** [kumahq/kuma#251]
For example:

```sh
$ kumactl get dataplanes
MESH      NAME        TAGS           STATUS   LAST CONNECTED AGO   LAST UPDATED AGO   TOTAL UPDATES   TOTAL ERRORS
default   dp-echo-1   service=echo   Online   4m47s                4m46s              2               0
```
and for the simplified version:

```sh
$ kumactl get dataplanes --compact
MESH      NAME        TAGS
default   dp-echo-1   service=echo
```

**Comment by jewertow** [comment]
@subnetmarco @nickolaev 
Is it still to be done? It looks like a good first issue and I would like to work on it, but I checked out these commands and for now they have more columns.
- `kumactl inspect dataplanes` returns additional columns `CERT REGENERATED AGO`, `CERT EXPIRATION`, `CERT REGENERATIONS`
- `kumactl get dataplanes` returns additional column `AGE`

**Comment by nickolaev** [comment]
@jewertow I am supportive of this change.

**Comment by jewertow** [comment]
@nickolaev I started working on it and I was trying to join these commands to achieve expected result, but I don't know what command `get` should print in case of formats json and yaml, because implementation of command `get dataplanes` reads a list of `DataplaneResource` and command `inspect dataplanes` reads a list of `DataplaneOverviewResource` which is wider. Let's look at these json outputs:
- json output of `inspect dataplanes`: https://github.com/Kong/kuma/blob/master/app/kumactl/cmd/inspect/testdata/inspect-dataplanes.golden.json
- json output of `get dataplanes`: https://github.com/Kong/kuma/blob/master/app/kumactl/cmd/get/testdata/get-dataplanes.golden.json
Could you help me?

**Comment by nickolaev** [comment]
@jewertow I would assume that the `--compact` version will produce the latter, i.e. the dataplanes resource. While without that argument it will output the more verbose  json/yaml.

**Comment by lahabana** [comment]
This can be reviewed once we have openAPI spec for Kuma as we'd consider a rewrite of kumactl

**Comment by lahabana** [comment]
Duping to #4297
