### ISSUE TITLE
Remove deprecated envoy listened ReusePort field

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2709]
### Summary

Once Kuma no longer needs to support Envoy 1.18, we can stop setting the deprecated listener `ReusePort` field.

**Comment by lahabana** [comment]
This is now possible as we're on a version >=1.18

**Comment by pouriyajamshidi** [comment]
Hi,

Is it ok if I work on this?

**Comment by lahabana** [comment]
Yes please go ahead @pouriyajamshidi !

**Comment by pouriyajamshidi** [comment]
The `circleCI` is indicating that `Envoy` is rejecting the config and that is because, we're now using `enableReusePort` instead of the deprecated `reusePort` field but the Envoy version in the test is `1.17.1` which does not support that option.  
I am not quite sure where this  `1.17.1` version comes from.
