### ISSUE TITLE
Expose metrics from k8s controller-runtime

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma#2927]
This issue is a followup from _@jakubdyszkiewicz question https://github.com/kumahq/kuma/pull/2764#discussion_r715605970_

[Exposed metrics are listed in the kubebuilder docs](https://book.kubebuilder.io/reference/metrics-reference.html)

One important use case is information about the state of the pod admission webhook

**Comment by Automaat** [comment]
This could be hard to do because all metrics are inside an internal package and not exposed for usage. Also there is open [issue](https://github.com/kubernetes-sigs/controller-runtime/issues/210) in `controller-runtime` about this. And another one closed where they ditched the topic: https://github.com/kubernetes-sigs/controller-runtime/issues/1995
