### ISSUE TITLE
Make Kuma's init container first by default

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#3121]
### Summary

Currently we append the Kuma init container to an existing list of init containers: https://github.com/kumahq/kuma/blob/2d08e3f8d63ffd75eb6e2cec5a8672f97044c77e/pkg/plugins/runtime/k8s/webhooks/injector/injector.go#L116 We should insert ourselves first by default to ensure that nothing 'slips through' before we can redirect traffic.

- This is a _change_ in default functionality, so should probably document it somewhere and call it out in the changelog (in case folks are somehow relying on us _not_ being first).
- Should we make this configurable? (prior art Hashicorp Vault: https://www.vaultproject.io/docs/platform/k8s/injector/annotations#vault-hashicorp-com-agent-init-first)

Worth calling out that if anything starts after our init but _before_ kuma-dp it's going to have no network access (unless the ports are explicitly ignored - `traffic.kuma.io/exclude-outbound-ports`)

Happy to make this change once we decide on the details above ^^.

**Comment by johnharris85** [comment]
Was thinking some more about this. We don't specify a reinvocationpolicy (https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#reinvocation-policy) and the default is never, so even if we put something first, another admission controller could absolutely re-order that without us knowing. If we were to set reinvocation to `ifneeded` then we would need additional logic to determine if we were already injected to be idempotent, I still don't think we're guaranteed to see the final state though unless we also implemented a validating hook to 'ensure' we were first. This probably needs a little more thought / consensus on how we want to move foward.

**Comment by lahabana** [comment]
Triage: Yes it makes sense

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's introduce config in Kuma CP to indicate if we want to inject by default first or last. Then, let's add an annotation to override this behavior.

**Comment by slonka** [comment]
This issue is needed to be able to implement this: https://github.com/kumahq/kuma/issues/2483 - any updates on development here?

**Comment by michaelgoodrx** [comment]
Hi, I got pointed to this issue from https://kuma-mesh.slack.com/archives/C013ALVE1GU/p1663005053300479.

We have init containers that need the internet to run. Specifically, they need the internet in order to decrypt secrets and generate a config file. So we actually need the kuma init container to go last, because as soon as it runs, there is no internet access until the sidecar starts.

It sounds like there are use cases where the init container should run first and use cases where the container should run last. It probably doesn't make sense to run it "in the middle".

Also, I noticed the thing about the admission controller too, and I have been a little nervous that one day the order of init containers would change and our apps would no longer start. So would definitely be in favor of setting up reinvocation to make sure it is in the "correct" order. RE https://github.com/kumahq/kuma/issues/3121#issuecomment-966745839

**Comment by lahabana** [comment]
I was just thinking this could be configurable through [container-patches](https://kuma.io/docs/1.8.x/explore/dpp-on-kubernetes/#custom-container-configuration).

Something like:

```yaml
apiVersion: kuma.io/v1alpha1
kind: ContainerPatch
metadata:
  name: container-patch-1
  namespace: kuma-system
spec:
   initOrder: first|last|<a specific integer>
```

**Comment by lahabana** [comment]
This was done by #5436

**Comment by michaelgoodrx** [comment]
@lahabana it looks to me like https://github.com/kumahq/kuma/pull/5436 only changed the order of the sidecar, not the init container.

**Comment by curtiscook** [comment]
> @lahabana it looks to me like #5436 only changed the order of the sidecar, not the init container.

IIRC the initcontainer goes first anyway. #5436 only changed the order, but we need to wait for the sidecar to be ready before the application start. I don't think you need #5857 to get the desired behavior

**Comment by curtiscook** [comment]
> > IIRC the initcontainer goes first anyway
> 
> In the version we are on, it runs last, which is important to us because we have other init containers that need internet access so they have to run before it.
> 
> But in my comment, I was pointing out that it looks like you closed this ticket, for changing the init container order, when you actually changed the sidecar order.

I didn't close the issue :) but I think there's confusion over this issue. The problem I've been working on addressing is that a container doesn't have DNS access after Init, before sidecar ready. Possible that my issue is separate from this one and we misattributed, but I think my understanding was that this issue was the kuma equivalent of https://github.com/istio/istio/issues/11130

That being said it looks like zekth change to run kuma init as the first init container has been merged so it seems moot?

**Comment by michaelgoodrx** [comment]
Sorry, I meant "you" as in Kong, I was assuming you worked for them.

Can you link me to the change that affects the init container? If that was merged then I need to open a ticket, because that breaks the mesh for us.

**Comment by curtiscook** [comment]
> Sorry, I meant "you" as in Kong, I was assuming you worked for them.
> 
> Can you link me to the change that affects the init container? If that was merged then I need to open a ticket, because that breaks the mesh for us.

Ah, no I'm a community edition user with a problem that I want to fix :) 

This should be the initcontainer pr
https://github.com/kumahq/kuma/pull/5857

**Comment by michaelgoodrx** [comment]
Thank you!
