### ISSUE TITLE
`kuma-dp-` tmpdir does not get cleaned up on service failure

### ISSUE THREAD

**Issue by jgrund** [kumahq/kuma#3194]
### What happened?

In the following code:

https://github.com/kumahq/kuma/blob/1fb6dd04bcfc112bb1e2e7415e2eb6b256bfcd28/app/kuma-dp/cmd/run.go#L103-L108

a tmpdir is created if both `cfg.DataplaneRuntime.ConfigDir` and `cfg.DNS.ConfigDir` are unset. This is done using `ioutil.TempDir`. `ioutil.TempDir` always places a random string in the dir it creates.

If a kuma-dp instance dies unexpectedly, the tmpdir does not get cleaned up. 

This can lead to a pathological case where a service dying repeatedly leaves many kuma-dp tmpdirs lying around, ultimately filling all the space available to /tmp.

This can be easily remedied by having a stable kuma-dp tmpdir name per instance. If the name is stable, then the previous  tmpdir can be removed on startup (or just the contents removed).

**Comment by jpeach** [comment]
This is in universal? Why don't you set the directories in config?

**Comment by jgrund** [comment]
> This is in universal? 

Yes

> Why don't you set the directories in config?

This is what I did, however the default settings allow this to happen. It wasn't until I hit the pathological case in production that I realized it was an issue.

**Comment by jpeach** [comment]
Ah I see, thanks for the explanation @jgrund. Setting a fixed directory by default can be problematic, since if it is a fixed path in /tmp, it might be subject to symlink attacks, and other common locations (e.g. /var/run) might not exist, or might need special handling if more than one kuma-dp is running. The current directory might not be writable.

I definitely agree that the deployment docs should recommend setting these directories. It's not totally clear to me why we need two separate configurations here either.

**Comment by jakubdyszkiewicz** [comment]
> Triage: Document this as a part of https://github.com/kumahq/kuma-website/issues/629
