### ISSUE TITLE
Http load balancing is not working with ingress

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3354]
### Description

The load balancing of HTTP traffic through the Kuma Ingress from another zone will not load balance across all the instances of the destination service, but only a subset depending on the number of CPU cores available on the ingress node.

To fix this we need to use an HTTP proxy on the Ingress, which implies terminating TLS on the Ingress in order to parse the HTTP request. But by doing so, we are sending an outgoing request to the intended destination service without any TLS information, unless the outgoing it's been re-encrypted with the original SANs so that nothing changes when the request is finally being received by the destination service.

This card needs a spike to determine what the available options are.

To replicate:

Create demo-client in zone-1
Create 3 instances of echo-server (kuma.io/protocol: http) in zone-2
Exec to demo-client and curl echo-server_kuma-test_svc_8080.mesh
Actual: all requests are balanced between 2 instances
Expected: all requests are balanced between all instances

**Comment by lahabana** [comment]
@lobkovilya this would be improved with egress in ingress isn't it?

**Comment by lahabana** [comment]
Some links from imports:

>We do use a weighted cluster, and apparently Consistent Hashing is not supported on it:

envoyproxy/envoy#8167
istio/istio#9764

**Comment by lobkovilya** [comment]
> this would be improved with egress in ingress isn't it?

Unfortunately no, Egress won't change that. The problem is that Ingress is essentially an L4 proxy because it doesn't terminate TLS. We can redesign Ingress to be a terminating proxy and behave sort of like MITM, but I guess it may bring some security concerns. Alternatively, Ingress may have its own `spiffe://mesh-1/ingress` identity, but then TrafficPermissions should explicitly mention this `ingress` as a source while today it's kind of transparent to users.

**Comment by lahabana** [comment]
Ha gotcha! Makes sense indeed.

**Comment by lahabana** [comment]
This is something that the current design doesn't enable us.
It doesn't seem to be causing much issues so closing.
