### ISSUE TITLE
Evaluate Gateway API controller conformance

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3450]
### Description

Once the Gateway API ingress controller is in reasonable shape, evaluate the [available conformance tests](https://github.com/kubernetes-sigs/gateway-api/issues/20) and investigate how to run them in the integration test harness.

**Comment by michaelbeaumont** [comment]
Spun off #3615

**Comment by michaelbeaumont** [comment]
I'll create a separate issue to track the "accuracy" of the conditions in terms of how much we can know about whether the proxies are actually serving the routes.

**Comment by jpeach** [comment]
steps to run conformance https://gist.github.com/jpeach/07c066bca292154ad280902816d3a649

**Comment by michaelbeaumont** [comment]
There were [some discussions around the meaning of the `Ready` statuses](https://kubernetes.slack.com/archives/CR0H13KGA/p1648564109363979) and it's planned for the conformance tests to assume eventual consistency instead of assuming immediate readiness, so that change in the fork will become unnecessary!
