### ISSUE TITLE
Tools for visibility: See which policy applies to gateway

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3720]
### Description

It currently only works for regular DPP

- [x] [`kumactl inspect dataplane <gateway-dataplane>`](https://github.com/kumahq/kuma/pull/3973)
- [x] [`kumactl inspect <policy-type> <policy>` with builtin gateways included in the output](https://github.com/kumahq/kuma/pull/3973)

**Comment by michaelbeaumont** [comment]
Do we want a `kumactl inspect gateway`? At the moment a user has to pick a specific `Dataplane` specifically, just like for sidecar dataplanes.

**Comment by lahabana** [comment]
I think it makes sense no?

**Comment by michaelbeaumont** [comment]
It does probably. Doing it also implies we should have something analogous like `kumactl inspect service` that does the same for normal `Dataplane`s.

**Comment by michaelbeaumont** [comment]
So it's a little tricky coming up with a fake `Dataplane`. `MeshGateways` support multiple tag selectors, each one requiring a `service` tag:

https://github.com/kumahq/kuma/blob/566b64d45afae4b295fd990d6231d5f1c1ca6bb0/api/mesh/v1alpha1/gateway.proto#L131-L134

so there's not always a "canonical" fake `Dataplane` we can come up with.

In the case of multiple selectors we could:

* return multiple inspect results, one per selector
* error
* pick one of the selectors
* *perhaps* use an empty `Dataplane` but the result of this won't be especially useful because it won't have a `service` tag and lots of policies won't show up since they select based on service tag.

**Comment by lobkovilya** [comment]
Does the first one imply specific Dataplane names in the output? Like:
```
gateway-1:
  *matched policies for gateway-1*
gateway-2:
  *matched policies for gateway-2*
```

**Comment by michaelbeaumont** [comment]
Hmm no, that's also an option though. My idea was simply to list which policies which match for a theoretical matching `Dataplane`. So even if there are no matching `Dataplane`s at the moment it returns some policies.

**Comment by lahabana** [comment]
Both sounds like it would make sense no? What's you opinion @lobkovilya ?

**Comment by michaelbeaumont** [comment]
> If we say that policy is something that has selectors, then MeshGateway is a policy in the first place

Indeed, our discussion in the catch up today made me realize the inconsistency in the commands.

I personally don't think it's useful to think of `MeshGateway` as a policy. IMO it's closer to `ZoneIngress` because it requires the `Dataplane` itself to elect to be a `Gateway`. Every `Dataplane` can serve at most one `Gateway`.

**Comment by michaelbeaumont** [comment]
> `ZoneIngress` doesn't require `Dataplane`, it's a proxy resource itself, so it's always 1 ZoneIngress -> 1 Envoy proxy (same for ZoneEgress). 

Yes, and a builtin Gateway `Dataplane` is the proxy resource, only the configuration is done via `MeshGateway`. A builtin Gateway Dataplane cannot do anything without a corresponding `MeshGateway`, unlike any other policy e.g. a ProxyTemplate.

`ZoneIngress` used to be a type of `Dataplane` itself. It only doesn't require a `Dataplane` now because there's no configuration necessary. If there were any room for `ZoneIngress`-specific configuration, it would end up looking exactly the same as `MeshGateway` does, otherwise the configuration would have to be repeated across `ZoneIngress` replicas.

**Comment by michaelbeaumont** [comment]
That's not to say the second option isn't useful, I think it's very useful. But in my opinion it would be a mistake to communicate to users that a `MeshGateway` is a policy because it hides the fact that a `MeshGateway` applies only to a special type of `Dataplane` and those `Dataplane`s require `MeshGateway`s.
