### ISSUE TITLE
universal CP on universal with memory backend - DP tries to connect but token is invalid?

### ISSUE THREAD

**Issue by pxpnetworks** [kumahq/kuma#3762]
### What happened?

Hello,

I have a general question about resiliency in case kuma-cp on universal with memory backend process restarts.
In my PoC i'm using Kuma 1.1.6  - the setup is the following:

1. server 1 runs kuma-cp binary
2. server 1 script creates mesh1 and a dataplane1 resource 
3. server 1 generates mesh1/dataplane1 token
4. server 2 runs kuma-dp binary -> everything is fine as long as connected to kuma-cp 
5. server 1 kuma-cp restart
6. server 1 again creates the same mesh1 and dataplane1 resources
7. server 1 creates the token again 
8. server 2 kuma-dp now throws this error:
[2022-01-28 15:02:01.685][20226][warning][upstream] [source/common/upstream/health_discovery_service.cc:329] StreamHealthCheck gRPC config stream closed: 2, **authentication failed: could not parse token: signature is invalid**

to be able to connect again to kuma-cp, kuma-dp needs to also restart (service interruption). 
Is there a way to reconnect the dataplane back to the control plane? As far as i remember way back when i did PoC with v0.6.0 when the CP disconnected the same procedure described above resulted in the dataplane connecting and becoming Online.

BR,
Stoyan

**Comment by jakubdyszkiewicz** [comment]
Hey, the problem is that in-memory storage type, storage is not persistent.
Whatever is the private key that was used to sign dataplane token is gone after you restart CP, therefore the token is invalid.

I'd recommend running a postgres, but you can also disable DP token authentication https://kuma.io/docs/1.4.x/security/dp-auth/#data-plane-proxy-token to not require token at all.
