### ISSUE TITLE
XDS config in Global CP

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#3789]
### Description

The current implementation of viewing XDS config in the GUI only support Standalone CP.
You can still use kumactl to connect to the Zone CP.

We should support viewing XDS config in Global CP. It requires some design how to forward a request from Global CP to Zone CP to Envoy.

**Comment by jakubdyszkiewicz** [comment]
# XDS in Global CP

## KDS Commands

We need to have a channel of communication between Global and Zone CP, to various operation since that won't be the last time we will need it (potentially: stats of DP, stats of CP, changing logging levels etc)

The initial implementation of KDS was created both ways. Global CP was connecting to Zone CP and there was a separate gRPC connection from Zone CP to Global CP. That was an operational nightmare, we should avoid it.

To avoid creating a connection from Global CP to Zone CP we can reuse KDS connection.
Because we need to send requests from Global CP to Zone CP we cannot use regular gRPC request/response service.
However, we can use bi-directional streaming.

```proto
service KdsCommands {
  rpc StreamXDSConfigs(stream XDSConfigResponse) returns (stream XDSConfigRequest);
}

message XDSConfigRequest {
  request_id = 1;

  resource_type = 1;
  resource_name string = 2;
  resource_mesh string = 3;
}

message XDSConfigResponse {
  request_id string = 1;
  error string = 2;

  config string = 3;
}
```

The flow is as following:
* Global CP put XDSConfigRequest to a stream and waits for the response
* Zone CP executes config dump on DP and puts XDSConfigResponse to a stream
* Global CP receives a response

KdsCommands service will be added to Global's KDS server.

**Comment by lobkovilya** [comment]
Are you sure we can reuse KDS connection? If you register `KdsCommands` service on `grpcServer` (alongside `MultiplexService`) then `KdsCommands` client will open another connection. And that's probably fine, because both connections will be in the same direction (from Zone to Global).

If we'd like to reuse connection, I think we should've nested `XDSConfigRequest/XDSConfigResponse` into `Message`:
```proto
```

**Comment by lobkovilya** [comment]
Or maybe you're right and it will be the same connection...

**Comment by jakubdyszkiewicz** [comment]
Sorry, bad wording on my side. When I typed "reuse connection" I meant
* We don't open separate port
* We don't need to write separate auth for it
* We don't need to build separate observability
etc.

This indeed will be a separate TCP connection.

**Comment by lobkovilya** [comment]
Probably we can implement a GRPC service that allows generic API calls from Global to Zone:
```proto
service ZoneAPIService {
  rpc StreamAPICalls(stream HTTPResponse) returns (stream HTTPRequest);
}

message HTTPResponse {
  string body = 1;
  uint32 statusCode = 2;
}

message HTTPRequest {
  string path = 1;
  string query = 2;
}
```
Maybe there are already `HTTPResponse` and `HTTPRequest` messages in GRPC libraries. 

In that case, whatever we implemented in Kuma API we can access from Global without creating special GRPC services for every occasion

**Comment by parkanzky** [comment]
The use case seems to align with bi-directional streaming.

@lobkovilya In your most recent comment are you suggesting that we further decode HTTP requests / responses, rather than encoding into protobuf? I think we should utilize protobuf's structure. Could we just extend the protobufs as we add communication types, instead of a generic HTTP encoding?

**Comment by jakubdyszkiewicz** [comment]
That's an interesting idea, but I'm not convinced for a couple of reasons
1) It requires an extra HTTP call. Although on localhost but still
2) Auth + RBAC for HTTP call
3) I _think_ (but I might be wrong) that there might be things that we want to expose only for Global CP, but not as an API.

**Comment by lahabana** [comment]
Agreed with @jakubdyszkiewicz I think it's better from both security and clarity to not allow unrestricted api calls by encapsulating HTTP requests in grpc.

However, It's strange it's a separate TCP connection, I thought the point of H2 was to be able to do multiplexing on a single TCP connection. Is this because it's a different GRPC service?

Maybe a way to avoid the multiplex stream in the future is to have a single service that does both KDS and Commands.
Multiplex stream is a very complex bit of code that has shown bugs in the past and I'd love it if this task provides a way forward for getting rid of the multiplexing (doesn't have to implement the new way though ;)).

Maybe we could do something like:

```proto
service GlobalKDSService {
  rpc GlobalToZoneStream(stream  envoy.service.discovery.v3.DiscoveryResponse) returns (stream envoy.service.discovery.v3.DiscoveryRequest);
  rpc ZoneToGlobalStream(stream  envoy.service.discovery.v3.DiscoveryRequest) returns (stream envoy.service.discovery.v3.DiscoveryResponse);
  rpc StreamXDSConfigs(stream XDSConfigRequest) returns (stream XDSConfigResponse);
  // Potentially in the future if zone needs to do requests to Global we can use unary requests.
  // e.g: rpc GlobalInfo() returns (GlobalInfoMetadata);
}
```

If we do so it removes all the multiplexing (each way has its own grpc stream) and gives us space to increase the API between zones and global while still having one TCP connection from zone to global.
