### ISSUE TITLE
why do you use envoy

### ISSUE THREAD

**Issue by fizz12344321** [kumahq/kuma#4540]
### Description

Hi, i am reading your project and i love it, can i ask u a question, why do you use Envoy in your project. Can you tell me the purpose, the pros and cons of this. thank u so much

**Comment by subnetmarco** [comment]
Envoy is being used primarily for its proxy I/O capabilities when processing request at the data plane layer. Since Envoy provides an easy to use dynamic API (the xDS API) that we can integrate with, and good support for the underlying proxy connectivity, we decided to focus on creating a strong control plane rather than reinventing the wheel on the data plane proxy layer, and decided to leverage Envoy proxy for that purpose. Hope this answers your question.
