### ISSUE TITLE
Choose a library for encoding YAML

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#5192]
### What happened?

All over the project we have 60 matches for `"github.com/ghodss/yaml"` and 5 matches for `"gopkg.in/yaml.v2"`. Ideally, we'd like to have a single library for this.

**Comment by lahabana** [comment]
This would makes sense as it seems we only use `yaml` tags in config which we can easily migrate. If we do this I guess we'll need to add something in golangci-lint to make sure we never use it

**Comment by lahabana** [comment]
Only concert with `ghodss` is that it's not really maintained anymore

**Comment by jakubdyszkiewicz** [comment]
> Triage: Options that we see right now
> 1) Add yaml and json tags everywhere and use `gopkg.in/yaml.v3`
> 2) Use `github.com/ghodss/yaml` but it has a dependency on `gopkg.in/yaml.v2` which might have security issues
> 3) Use fork of `github.com/ghodss/yaml` called `https://github.com/invopop/yaml` which may not be battle tested

**Comment by mmorel-35** [comment]
Hi !
Do you knoaw , that you also have `sigs.k8s.io/yaml` as a for of `github.com/ghodss/yaml` which is already present as an indirect dependency ?

**Comment by lahabana** [comment]
@mmorel-35 suggestions makes sense. In the end there's little benefit in using: yaml.v3 (see: https://github.com/go-yaml/yaml/tree/v3#compatibility CVEs are fixed in newer versions: https://security.snyk.io/package/golang/gopkg.in%2Fyaml.v2 ) and staying on what k8s does is probably the best choice.

So in the end we'd use `sigs.k8s.io/yaml` for everything and disallow using `github.com/ghodss/yaml` and `gopkg.in/yaml*` directly. 

@lobkovilya @jakubdyszkiewicz WDYT?

**Comment by jakubdyszkiewicz** [comment]
Works for me 👍
