### ISSUE TITLE
Idempotent builds

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#5270]
### Description

Right now, we have no way to cache image builds. Images are always rebuilt because the binaries depend on the build date:https://github.com/kumahq/kuma/blob/abf0346477a9e8d4dba0f0c74a1c06fd7d782e83/mk/build.mk#L3

It's been discussed before https://github.com/kumahq/kuma/pull/4713

**Comment by slonka** [comment]
There is a couple of things going on here:

1. > Images are always rebuilt because the binaries depend on the build date

That is true but that is not the only reason. Docker will not cache a build if the creation / modification date is different, so even though we produce the same binary it wont be cached.

2. What takes a lot of time now is sending big binaries to the context.

3. All our images share the same build context (`.` directory) so running `make images` will build `kuma-cp` that will invalidate build context for the next image (e.g. `kuma-dp`) so even if we get docker to cache individual images it will not improve the overall `make images` time.

So what can we do about this?

1. Rearrange our repo to have separate build context for each image so that build context can be cached.

This would be something like this for kuma-cp: 
- the binary is built to `app/kuma-cp/build/artifacts-darwin-arm64/kuma-cp`
- the context is set to `app/kuma-cp`
- other artifacts (license etc.) are copied to `app/kuma-cp/build`

2. Build our images from sources in docker using multistage builds (so we don't transfer big files? but we will transfer a lot of smaller files - not sure it would be faster).

**Comment by michaelbeaumont** [comment]
> 2. Build our images from sources in docker using multistage builds (so we don't transfer big files? but we will transfer a lot of smaller files - not sure it would be faster).

That's my vote. Anything else feels like more fighting against docker. Granted, it's perhaps not trivial to express how to build our binaries in docker but it has the nice side effect that builds are also reproducible.

Having universal binaries probably complicates this. Or can you copy the binary out of a docker image and use that? No idea

> 1. Rearrange our repo to have separate build context for each image so that build context can be cached.

But also this doesn't seem like that much work either.

**Comment by slonka** [comment]
Checked that istio does 1. - https://github.com/istio/istio/blob/0d59fec221cc55a0800ae09ab680247fb58b63ef/tools/docker.yaml#L1 and they have a dedicated tool (I don't think we need that).

**Comment by jakubdyszkiewicz** [comment]
Both options are ok to me.
Might be obvious, but if we go with 2. I still would like to build Kuma without Docker if I'm building just the binaries

**Comment by lahabana** [comment]
> 2. What takes a lot of time now is sending big binaries to the context.

How much of the time is spent there?

**Comment by slonka** [comment]
For `kuma-cp` on my machine it is - `21.00` seconds fresh build, `3.54` cached build - `83%`. For `kuma-dp` fresh build is `12.99` and `4.73` - `63%`. For `kuma-init` it is `11.08` and `3.47` - `68%`.

**Comment by slonka** [comment]
Attaching logs for the builds I mention.

[idempotent-build-times-logs.txt.zip](https://github.com/kumahq/kuma/files/9970924/idempotent-build-times-logs.txt.zip)

**Comment by bartsmykla** [comment]
I'm fine with both solutions as well, but if gains are so significant, I think it should be worth to spend some time and go with the 1st proposition.
