### ISSUE TITLE
TLS listener support

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#6132]
### Description

Implement TLS (not HTTPS) `MeshGateway` listener support. This includes `PASSTHROUGH` mode.

**Comment by andrey-dubnik** [comment]
Hi, we are currently validating the scenario where private network services where DP can't be installed must access the services on the Mesh and External services via the Mesh Gateway. Few of the services are TCP services requiring the mTLS hence we need to use the TLS PASSTHROUGH so the TLS connection is not terminated. It would be great if build-in gateway included a support for the TLS PASSTHROUGH.

**Comment by andrey-dubnik** [comment]
Still relevant as otherwise TCP connection to the external service is hard to manage for the mTLS scenario.

**Comment by michaelbeaumont** [comment]
> Few of the services are TCP services requiring the mTLS hence we need to use the TLS PASSTHROUGH so the TLS connection is not terminated

@andrey-dubnik Can you clarify how you expect passthrough mode to help? The use case for passthrough mode would be where a service behind the gateway is itself listening over TLS, _inside_ the mesh. I.e. it isn't to allow gateway consumers to access services protected by Kuma's mTLS.

**Comment by andrey-dubnik** [comment]
If we have an external TCP service which is TLS enabled we would like to publish it on a mesh gateway without having to configure the TLS on the gateway explicitly. This works with HA proxy (gateway mode) at the moment but Kuma requires TLS explicitly enabled on the gateway otherwise client fails to connect due to no TLS where the actual server requires one.
