### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by subnetmarco** [kumahq/kuma#706]
Provide Helm chart for Kuma.

**Comment by nickolaev** [comment]
I was thinking about what could be our best approach here. Today we rely on `kumactl install control-plane | kubectl apply -f -` to deploy Kuma on Kubernetes. This, of course, suggests that `kumactl` already includes some of the functionality that a potential Helm chart might want to implement. So in order to have the same experience no matter which deployment method one chooses we can:
 * develop both options in parallel and keep them in sync
 * have automated tooling that generates the embedded resources in `kumactl` and the Helm charts
 * have a simple Helm chart that just runs a `kumactl` docker image as Cluster Admin and then executes `kumactl install control-plane | kubectl apply -f -` from within it

I personally like the last option as it will allow for more streamlined development deployment, and not proliferate the entities needed to maintain. On the downside, in this scenario the Helm Chart will have to ensure Cluster Admin privileges for the said `kumactl` container during the time of its execution.

Any opinions?

**Comment by sayboras** [comment]
I think I asked for this feature in slack channel before. Understand that using cli install command and then kubectl apply is a very common approach, which is used in istio as well. However, it's hard with versioning and changing configuration to meet consumers' requirement. 

One simple use case in EKS is to control permission using annotation in service account, more and more simple use cases like this are coming day by day I think. Not sure with the last option, how easy to customize values.yaml like maintaining in separate helm chart.

**Comment by tharun208** [comment]
I think we can simply create a chart for our `kuma-cp` and deploy it inside k8's. The `kuma-cp` modes can be specified using the `values.yaml`.
