### ISSUE TITLE
Handle OpenMetrics prometheus metrics from applications

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#7093]
### What happened?

After https://github.com/kumahq/kuma/pull/6783 prometheus can't scrape targets and returns the following error, so it was reverted. This issue covers this feature

![image](https://github.com/kumahq/kuma/assets/12110261/110b1ae1-531c-44c3-b4da-613113405c40)

**Comment by AyushSenapati** [comment]
`expfmt.NegotiateIncludingOpenMetrics()` only gets called when the hijacker fails to find a valid ContentType (CT) returned by the target applications. Upon debugging,  it was found that Envoy returns `Content-Type": "text/plain; charset=UTF-8"` with out the version param. In result the `responseFormat()` is returning `expfmt.FmtUnknown` as we also validate the version param, which is why `expfmt.NegotiateIncludingOpenMetrics()` is called and it would return highest CT supported by the Prometheus Scraper (In our case this is `expfmt.FmtOpenMetrics_1_0_0`).

The actual metrics content of Envoy was `text/plain` but the Hijacker sets the CT header to Openmetrics, which is why prom scraper is failing to process.

I will update the Mutator to normalise the metrics content.

**Comment by jakubdyszkiewicz** [comment]
was it solved? Because I see

![image](https://github.com/kumahq/kuma/assets/5459824/f00f873f-1b0f-4bec-b520-acddcf3a17ac)
