### ISSUE TITLE
[iptables] Possibility to exclude port from iptables at control-plane level

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#7722]
### Description

It would be nice if you could exclude some ports from routing at the global level. Lets say your whole cluster needs to report metrics to service at port `8126` but it cannot go through sidecar. You could globally exclude this for each init container.

**Comment by lahabana** [comment]
@lukidzi there's already `--exclude-ports` that is getting improved with: https://github.com/kumahq/kuma/pull/7588

Is this something that doesn't work for you?

**Comment by lukidzi** [comment]
Isn't it just for one sidecar by annotation? I thought about - what if I want to disable one port for all pods in the cluster/zone

**Comment by jijiechen** [comment]
Let me take this one

**Comment by jijiechen** [comment]
> Isn't it just for one sidecar by annotation? I thought about - what if I want to disable one port for all pods in the cluster/zone

So the initial idea is to enlarge the scope that a port-excluding rule can apply to. Is it better to apply this scope at the `Mesh` level instead of the global control plane level? 

One other question would be, should we also support excluding ports for inbound traffic?

The ports are taken into account by the `kuma-init` container which is auto injected. So the implementation will introduce a change to the injector:

1. add fields into API protocol of 'Mesh.Networking' object:
  1. Outbound.ExcludedPorts repeated `uint32`
  2. Inbound.ExcludedPorts repeated `uint32`
2. Fetch the Mesh object that the Pod/Namespace belongs to
3. Read Mesh level settings and merge it with pod level settings (by annotations)
4. Apply the result into init container generating

Any ideas? 
@lahabana @lukidzi

**Comment by lahabana** [comment]
There's multiple issues in adding fields to the dataplane object:

- One assumption is that this works on both k8s and universal, we currently don't have a way to configure `install tp` from the cp.
- Dataplane object is supposed to be dynamically updated

I feel like either we should use a k8s only primitive or let users do this themselves with a webhook.

One option could be to extend further [ContainerPatch](https://kuma.io/docs/dev/production/dp-config/dpp-on-kubernetes/#custom-container-configuration) ? I know that there was another use case for adding volumes to pods systematically too.

**Comment by jijiechen** [comment]
And by the way, it seems we currently do support a global configuration for Kubernetes based intallation:

- yaml configuration: `runtime.kubernetes.injector.sidecarContainer.waitForDataplaneReady`
- environment variable: `kuma_runtime_kubernetes_sidecar_traffic_exclude_inbound_ports`

See code in [injector.go](https://github.com/kumahq/kuma/blob/master/pkg/plugins/runtime/k8s/webhooks/injector/injector.go#L601)

Does this match the requirement? @lukidzi

**Comment by lahabana** [comment]
@lukidzi can you answer @jijiechen question?

**Comment by lukidzi** [comment]
@jijiechen You are right it seems to be supported with `kuma_runtime_kubernetes_sidecar_traffic_exclude_inbound_ports` and `kuma_runtime_kubernetes_sidecar_traffic_exclude_outbound_ports`
