### ISSUE TITLE
rollout restart doesn't work on deployment behind a MeshGatewayInstance

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#9476]
### What happened?

IIRC you do `kubectl rollout restart deployment <my-gateway-instance>` you then see the first pod good to `terminating` and it then switches back to running.

It's odd but was very easy to repro

**Comment by jakubdyszkiewicz** [comment]
> Triage: look at deployment and replicaset. It's impossible for Pod to go from Terminating to Running.

**Comment by Automaat** [comment]
I was able to reproduce it with latest Kuma 2.8.0. What happens after running `kubectl rollout restart deployment <my-gateway-instance>`:

A new instance is created but it is removed immediately. From events:
```
Normal  ScalingReplicaSet  7m24s                  deployment-controller  Scaled up replica set demo-app-gateway-5c4cd96db7 to 1
Normal  ScalingReplicaSet  7m24s                  deployment-controller  Scaled down replica set demo-app-gateway-5c4cd96db7 to 0
```

When running, `rollout restart` Kubernetes will update Deployment and change `replicas` value to n+1 (where n is previous number of replicas), at the same time our controller will be triggered and will decrease number of replicas to value specified in `MeshGatewayInstance`. So the newly created pod which is not yet healthy, will get terminated immediately. 

This happens because of: https://github.com/kumahq/kuma/blob/92218c0d8cc1533614397e97cc4efb3c77467dcb/pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go#L331

**Comment by Automaat** [comment]
It is most likely that my previous explanation does not make sense, but the issue is there
